# Dev image: PHP + Composer + Node
FROM php:8.2-fpm

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git unzip zip curl \
    libzip-dev libpng-dev libonig-dev libxml2-dev libpq-dev \
    libicu-dev \
 && docker-php-ext-install \
    pdo pdo_mysql pgsql pdo_pgsql mbstring zip exif pcntl bcmath gd intl

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer install
